- name: Get yarn cache
  id: yarn-cache-dir-path
  run: echo "::set-output name=dir::$(yarn cache dir)"

- name: Cache dependencies
  uses: actions/cache@v2
  # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
  id: yarn-cache 
  with:
    path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
    key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    restore-keys: |
      ${{ runner.os }}-yarn-